### ISSUE TITLE
Pretrained weight files not found

### ISSUE THREAD

**Issue by Mahmood-Hussain** [clxia12/RT-DETRv3#2]
Hi, I can not download the download link on your github doesn't take me to any external website for download and when I run 
```bash
python tools/export_model.py -c configs/rtdetrv3/rtdetrv3_r18vd_6x_coco.yml               -o weights=https://bj.bcebos.com/v1/paddledet/models/rtdetrv3_r18vd_6x_coco.pdparams trt=True               --output_dir=output_inference
```
that gives me 404 error 

```
[12/23 10:16:52] ppdet.utils.download INFO: Downloading rtdetrv3_r18vd_6x_coco.pdparams from https://bj.bcebos.com/v1/paddledet/models/rtdetrv3_r18vd_6x_coco.pdparams
Traceback (most recent call last):
  File "/home/e300/mahmood/code/RT-DETRv3/tools/export_model.py", line 118, in <module>
    main()
  File "/home/e300/mahmood/code/RT-DETRv3/tools/export_model.py", line 114, in main
    run(FLAGS, cfg)
  File "/home/e300/mahmood/code/RT-DETRv3/tools/export_model.py", line 77, in run
    trainer.load_weights(cfg.weights)
  File "/home/e300/mahmood/code/RT-DETRv3/ppdet/engine/trainer.py", line 483, in load_weights
    load_pretrain_weight(self.model, weights, ARSL_eval)
  File "/home/e300/mahmood/code/RT-DETRv3/ppdet/utils/checkpoint.py", line 238, in load_pretrain_weight
    pretrain_weight = get_weights_path(pretrain_weight)
  File "/home/e300/mahmood/code/RT-DETRv3/ppdet/utils/download.py", line 139, in get_weights_path
    path, _ = get_path(url, WEIGHTS_HOME)
  File "/home/e300/mahmood/code/RT-DETRv3/ppdet/utils/download.py", line 295, in get_path
    fullname = _download_dist(url, root_dir, md5sum)
  File "/home/e300/mahmood/code/RT-DETRv3/ppdet/utils/download.py", line 424, in _download_dist
    return _download(url, path, md5sum)
  File "/home/e300/mahmood/code/RT-DETRv3/ppdet/utils/download.py", line 371, in _download
    raise RuntimeError("Downloading from {} failed with code "
RuntimeError: Downloading from https://bj.bcebos.com/v1/paddledet/models/rtdetrv3_r18vd_6x_coco.pdparams failed with code 404!

```

**Comment by clxia12** [comment]
Thank you for your interest in our approach. You can find the corresponding weight files in the download symlink.

**Comment by Linaamri28** [comment]
Is an inference available for this model or I need to train it ?
